book/urls.py
from django.urls import include, path

from .views import BookList, BookDetail, BookCategory, BookSearch, AuthorList, AuthorDetail

author_patterns = [
    path('', AuthorList.as_view(), name='author_list'),
    path('<slug:slug>/', AuthorDetail.as_view(), name='author_detail'),
]

urlpatterns = [
    path('', BookList.as_view(), name='book_list'),
    path('category/<str:category>', BookCategory.as_view(), name='book_category'),
    path('search/', BookSearch.as_view(), name='book_search'),
    path('<slug:slug>', BookDetail.as_view(), name='book_detail'),

    path('author/', include(author_patterns)),


]

bookweb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from book.views import HomeView


urlpatterns = [
    path('', HomeView.as_view()),
    path('admin/', admin.site.urls),
    path('books/', include(('book.urls', 'books'), namespace='books')),
    # path('authors/', include(('author.urls'), namespace='authors')),
   ]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

book/models.py
from django.db import models
from django.utils.text import slugify
import json



class Author(models.Model):
    author = models.CharField(max_length=100)
    date_of_birth = models.DateField()
    date_of_death = models.DateField(null=True, blank=True)
    nationality = models.CharField(max_length=100)
    image = models.ImageField(upload_to='authors')
    description = models.TextField(max_length=1000)
    slug = models.SlugField(blank=True, null=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.author)
        super(Author, self).save(*args, **kwargs)

    def __str__(self):
        return self.author


CATEGORY_BOOKS = {
    ("fantasy", "FANTASY"),
    ("sci_fi", "SCI_FI"),
    ("horror", "HORROR"),
    ("biographies", "BIOGRAPHIES"),
    ("romance", "ROMANCE"),
    ("thrillers", "THRILLER"),
}

class Book(models.Model):
    objects = None
    title = models.CharField(max_length=100)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    publisher = models.CharField(max_length=100)
    image = models.ImageField(upload_to='books')
    data_of_production = models.DateField()
    category = models.CharField(choices=CATEGORY_BOOKS, max_length=15)
    description = models.TextField(max_length=1000)
    main_characters = models.CharField(max_length=200)
    series = models.CharField(max_length=100, blank=True)
    film_adaptation = models.BooleanField(default=False)
    movie_trailer = models.URLField(blank=True)
    tags = models.CharField(max_length=100)
    views_count = models.IntegerField(default=0)

    slug = models.SlugField(blank=True, null=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Book, self).save(*args, **kwargs)


    def __str__(self):
        return self.title

book/views.py
from django.views.generic import ListView, DetailView
from .models import Book, Author
from django.db.models import Q, F
# Create your views here.


class HomeView(ListView):
    model = Book
    template_name = 'book/home.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context["new_book"] = Book.objects.all().order_by("-data_of_production")
        context["popular_book"] = Book.objects.all().order_by("-views_count")
        return context


class BookList(ListView):
    model = Book
    paginate_by = 5


class BookDetail(DetailView):
    model = Book

    def get_object(self, queryset=None):
        book_object = super().get_object()
        book_object.view_count = F('view_count') + 1
        book_object.save()

        return book_object

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['book_series'] = Book.objects.filter(Q(series=self.get_object().series)).filter(~Q(series=""))

        if Book.objects.filter(Q(series=self.get_object().series)).filter(~Q(series="")):
            context['book_category'] = Book.objects.filter(Q(category=self.get_object().category)).exclude(
                Q(series=self.get_object().series))
        else:
            context['book_category'] = Book.objects.filter(Q(category=self.get_object().category))

        return context


class BookCategory(ListView):
    model = Book
    paginate_by = 5

    def get_queryset(self):
        self.category = self.kwargs['category']
        return Book.objects.filter(category=self.category)


class BookSearch(ListView):
    model = Book
    paginate_by = 5
    template_name = 'book/search.html'

    def get_queryset(self):
        query = self.request.GET.get('query')
        if query:
            object_list = self.model.objects.filter(Q(title__icontains=query) | (Q(author__author__icontains=query)))
        else:
            object_list = self.model.objects.none()
        return object_list


class AuthorList(ListView):
    model = Author
    paginate_by = 5
    template_name = 'book/author_list.html'


class AuthorDetail(DetailView):
    model = Author

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['author_books'] = Book.objects.filter(author=self.get_object())
        return context

book/templates/book/author_detail.html
{% extends 'base.html' %}
{% block  content %}

<main class="content">
    <div class="single cf">

        <section class="book cf">
            <img src="{{object.image.url}}">
            <ul>
                <li>{{object.author }}</li>
                <li>Date of birth: {{object.date_of_birth }}</li>
                {% if object.date_of_death%}
                <li>Date of death: {{object.date_of_death }}</li>
                {% endif%}
                <li>Nationality: {{object.nationality }}</li>
                <li>{{object.description}}</li>

            </ul>
        </section>

        {%if author_books %}
        <section class="related cf">
            <div class="books cf">
                <h3>Books: </h3>
                <!-- Swiper -->
                <div id="authors-books" class="swiper-container">
                    <div class="swiper-wrapper">
                        {% for book in author_books %}
                        <div class="swiper-slide mov">
                            <a href="{% url 'books:book_detail' book.slug %}">
                                <img src="{{book.image.url}}">
                                <h2 class="booktitle">{{book.title}}</h2>
                            </a>
                        </div>
                        {% empty %}
                        <h3>Actually there are no books in this category</h3>
                        {% endfor%}
                    </div>
                    <!-- Add Pagination -->
                    <div class="swiper-pagination"></div>
                </div>
            </div>

        </section>
        {% endif %}

    </div>
</main>

{% endblock %}

{% block  scripts %}
<!-- Initialize Swiper -->
<script>
 $(document).ready(function(){
    var swiper = new Swiper(
        '#authors-books',
         {
          slidesPerView: 5,
          spaceBetween: 30,
          freeMode: true,
          pagination: {
            el: '.swiper-pagination',
            clickable: true,
          },
        }
    );
 });

</script>
{% endblock %}

book/templates/book/author_list.html
{% extends 'base.html' %}
{% block  content %}
		<main class="content">
			<section class="centered">
				<div class="books">
                    {% for author in author_list %}
					<div class="mov">
						<a href="{% url 'books:author_detail' author.slug %}">
							<img src="{{author.image.url}}">
							<h2 class="booktitle">{{author.author}}</h2>
						</a>
					</div>
					{% endfor%}
				</div>
                {% if is_paginated %}
				<nav class="pagination">
					<ul>
                        {% if page_obj.has_previous %}
						    <li><a href="?page={{ page_obj.previous_page_number }}">Prev</a></li>
                        {% else %}
                            <li class="disabled"></li>
                        {% endif %}

                        {% for pages in page_obj.paginator.page_range %}
                            {% if page_obj.number == pages %}
						        <li><a href="#">{{pages}}</a></li>
                            {% else %}
                                 <li><a href="?page={{pages}}">{{pages}}</a></li>
                            {% endif %}
						{% endfor%}

                        {% if page_obj.has_next %}
						    <li><a href="?page={{page_obj.next_page_number }}">Next</a></li>
                        {% else %}
                            <li class="disabled"></li>
                        {% endif %}
					</ul>
				</nav>
                {% endif %}
			</section>

		</main>
{% endblock %}

book/templates/book/book_detail.html
{% extends 'base.html' %}
{% block  content %}
<main class="content">
    <div class="single">

        <section class="book">
            <img src="{{object.image.url}}">
            <ul>
                <li>{{object.title }}</li>
                <li><a href="{% url 'books:author_detail' book.author.slug %}">Author: {{object.author }}</a></li>
                <li>Publisher: {{object.publisher }}</li>
                <li>Date: {{object.data_of_production }}</li>
                <li>{{object.description}}</li>
                <li>Main Characters: {{object.main_characters}}</li>
                <li><a href="{% url 'books:book_category' book.category %}">{{object.category}}</a>
<!--                <li><a href="/">{{object.tags}}</a>-->
                <li>{{object.views_count}} Views</li>
            </ul>
        </section>
        {%if object.movie_trailer %}
        <section class="trailer">
            <h3>Film Adaptation: </h3>
            <div class="trailer_frame">
                <iframe width="560" height="315" src="{{object.movie_trailer}}" frameborder="0"
                        allowfullscreen></iframe>
            </div>
        </section>
        {% endif %}

        {%if object.series %}
        <section class="related">
            <div class="books">
                <h3>Series: {{object.series }}</h3>
                <!-- Swiper -->
                <div id="series-books" class="swiper-container">
                    <div class="swiper-wrapper">
                        {% for book in book_series %}
                        <div class="swiper-slide mov">
                            <a href="{% url 'books:book_detail' book.slug %}">
                                <img src="{{book.image.url}}">
                                <h2 class="booktitle">{{book.title}}</h2>
                            </a>
                        </div>
                        {% endfor%}
                    </div>
                    <!-- Add Pagination -->
                    <div class="swiper-pagination"></div>
                </div>
            </div>

        </section>
        {% endif %}

        {%if object.category %}
        <section class="related">
            <div class="books">
                <h3>{{object.category }} books: </h3>
                <!-- Swiper -->
                <div id="category-books" class="swiper-container">
                    <div class="swiper-wrapper">
                        {% for book in book_category %}
                        <div class="swiper-slide mov">
                            <a href="{% url 'books:book_detail' book.slug %}">
                                <img src="{{book.image.url}}">
                                <h2 class="booktitle">{{book.title}}</h2>
                            </a>
                        </div>
                        {% empty %}
                        <h3>Actually there are no books in this category</h3>
                        {% endfor%}
                    </div>
                    <!-- Add Pagination -->
                    <div class="swiper-pagination"></div>
                </div>
            </div>

        </section>
        {% endif %}

    </div>
</main>
{% endblock %}

{% block styles %}
<style>
    <!--html, body {-->
      <!--position: relative;-->
      <!--height: 100%;-->
    <!--}-->
    <!--body {-->
      <!--background: #eee;-->
      <!--font-family: Helvetica Neue, Helvetica, Arial, sans-serif;-->
      <!--font-size: 14px;-->
      <!--color:#000;-->
      <!--margin: 0;-->
      <!--padding: 0;-->
    <!--}-->
    .swiper-container {
      width: 100%;
      height: 100%;
    }
    .swiper-slide {
      <!--text-align: center;-->
      <!--font-size: 18px;-->
      <!--background: #fff;-->
      <!--/* Center slide text vertically */-->
      <!--display: flex;-->
      <!--align-items: center;-->
    }

</style>
{% endblock %}

{% block  scripts %}

<!-- Initialize Swiper -->
<script>
    var swiper = new Swiper('#series-books', {
      slidesPerView: 5,
      spaceBetween: 30,
      freeMode: true,
      pagination: {
        el: '.swiper-pagination',
        clickable: true,
      },
    });
    var swiper = new Swiper('#category-books', {
      slidesPerView: 5,
      spaceBetween: 30,
      freeMode: true,
      pagination: {
        el: '.swiper-pagination',
        clickable: true,
      },
    });

</script>
{% endblock %}

book/templates/book/book_list.html
{% extends 'base.html' %}
{% block  content %}
		<main class="content">
			<section class="centered">
				{% if book_category%}
				<h3>Category: {{book_category|title}}</h3>
				{% endif %}
				<div class="books">
                    {% for book in object_list %}
					<div class="mov">
						<a href="{% url 'books:book_detail' book.slug %}">
							<img src="{{book.image.url}}">
							<h2 class="booktitle">{{book.title}}</h2>
						</a>
					</div>
					{% empty %}
						<h3>Cannot find a book that meets your criteria</h3>
					{% endfor%}
				</div>
                {% if is_paginated %}
				<nav class="pagination">
					<ul>
                        {% if page_obj.has_previous %}
						    <li><a href="?page={{ page_obj.previous_page_number }}">Prev</a></li>
                        {% else %}
                            <li class="disabled"></li>
                        {% endif %}

                        {% for pages in page_obj.paginator.page_range %}
                            {% if page_obj.number == pages %}
						        <li><a href="#">{{pages}}</a></li>
                            {% else %}
                                 <li><a href="?page={{pages}}">{{pages}}</a></li>
                            {% endif %}
						{% endfor%}

                        {% if page_obj.has_next %}
						    <li><a href="?page={{page_obj.next_page_number }}">Next</a></li>
                        {% else %}
                            <li class="disabled"></li>
                        {% endif %}
					</ul>
				</nav>
                {% endif %}
			</section>

		</main>
{% endblock %}

book/templates/book/home.html
{% extends 'base.html' %}
{% load static %}
{% block  content %}
<main class="content">
    <div class="homeslider">
        <div class="swiper-container">

            <div class="swiper-wrapper">
                <div class="swiper-slide">
                    <img src="{% static 'img/banner.jpg'%}">
                    <div class="caption">
                        <div class="captioninside">
                            <h3>BookWeb</h3>
                            <p>Description of a thousand books in one place</p>
                        </div>
                    </div>
                </div>

                <!-- Add Pagination -->
            </div>
        </div>
        <section class="panel">
            <h2>New</h2>
            <div id="new-books-slider" class="mostslider">
                <div class="swiper-container">
                    <div class="swiper-wrapper">
                        {% for book in new_book %}
                        <div class="swiper-slide mov">
                            <a href="{% url 'books:book_detail' book.slug %}">
                                <img src="{{book.image.url}}">
                                <h2 class="booktitle">{{book.title}}</h2>
                            </a>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>

            <h2>Popular</h2>

            <div id="popular-books-slider" class="mostslider">
                <div class="swiper-container">
                    <div class="swiper-wrapper">
                        {% for book in popular_book %}
                        <div class="swiper-slide mov">
                            <a href="{% url 'books:book_detail' book.slug %}">
                                <img src="{{book.image.url}}">
                                <h2 class="booktitle">{{book.title}}</h2>
                            </a>
                        </div>
                        {% endfor %}
                    </div>
                    <!-- Add Pagination -->
                </div>
            </div>
        </section>
    </div>
</main>
{% endblock %}

{% block  scripts %}

<!-- Initialize Swiper -->
<script>
   $(document).ready(function(){
				var swiper = new Swiper('.homeslider > .swiper-container', {
					pagination: '.swiper-pagination',
					paginationClickable: true,
					preventClicks:false,
					preventClicksPropagation:false,
					effect:'fade',
					breakpoints: {
						320: {
							height:200
						},

						480: {
							height:300
						},

						768: {
							height:400
						},
						1024: {
							height:500
						}
					}
				});

				var recentswiper = new Swiper('.recentslider > .swiper-container', {
					nextButton: '.recent-next',
					prevButton: '.recent-prev',
					slidesPerView: 8,
					paginationClickable: true,
					preventClicks:false,
					preventClicksPropagation:false,
					spaceBetween: 10,
					breakpoints: {
						320: {
							slidesPerView: 3,
							spaceBetween: 5
						},

						480: {
							slidesPerView: 3,
							spaceBetween: 5
						},

						768: {
							slidesPerView: 5,
							spaceBetween: 5
						},
						1024: {
							slidesPerView: 6,
							spaceBetween: 10
						}
					}
				});



				var mostswiper = new Swiper('#new-books-slider > .swiper-container', {
					nextButton: '.most-next',
					prevButton: '.most-prev',
					slidesPerView: 8,
					paginationClickable: true,
					preventClicks:false,
					preventClicksPropagation:false,
					spaceBetween: 10,
					breakpoints: {
						320: {
							slidesPerView: 3,
							spaceBetween: 5
						},

						480: {
							slidesPerView: 3,
							spaceBetween: 5
						},

						768: {
							slidesPerView: 5,
							spaceBetween: 5
						},
						1024: {
							slidesPerView: 6,
							spaceBetween: 10
						}
					}
				});

				var mostswiper = new Swiper('#popular-books-slider > .swiper-container', {
					nextButton: '.most-next',
					prevButton: '.most-prev',
					slidesPerView: 8,
					paginationClickable: true,
					preventClicks:false,
					preventClicksPropagation:false,
					spaceBetween: 10,
					breakpoints: {
						320: {
							slidesPerView: 3,
							spaceBetween: 5
						},

						480: {
							slidesPerView: 3,
							spaceBetween: 5
						},

						768: {
							slidesPerView: 5,
							spaceBetween: 5
						},
						1024: {
							slidesPerView: 6,
							spaceBetween: 10
						}
					}
				});

				var topswiper = new Swiper('.topslider > .swiper-container', {
					nextButton: '.top-next',
					prevButton: '.top-prev',
					slidesPerView: 8,
					paginationClickable: true,
					preventClicks:false,
					preventClicksPropagation:false,
					spaceBetween: 10,
					breakpoints: {
						320: {
							slidesPerView: 3,
							spaceBetween: 5
						},

						480: {
							slidesPerView: 3,
							spaceBetween: 5
						},

						768: {
							slidesPerView: 5,
							spaceBetween: 5
						},
						1024: {
							slidesPerView: 6,
							spaceBetween: 10
						}
					}
				});

			});

</script>
{% endblock %}

book/templates/book/search.html
{% extends 'base.html' %}
{% load mytemplatetags %}
{% block  content %}

		<main class="content">
			<section class="centered">
				{% if book_category%}
				<h3>Category: {{book_category|title}}</h3>
				{% endif %}
				<div class="books">
                    {% for book in object_list %}
					<div class="mov">
						<a href="{% url 'books:book_detail' book.slug %}">
							<img src="{{book.image.url}}">
							<h2 class="booktitle">{{book.title}}</h2>
						</a>
					</div>
					{% empty %}
						<h3>Cannot find a book that meets your criteria</h3>
					{% endfor%}
				</div>
                {% if is_paginated %}
				<nav class="pagination">

					<ul>
                        {% if page_obj.has_previous %}
						     <li><a href="?{% url_replace request 'page' page_obj.previous_page_number %}">Prev</a></li>
                        {% else %}
                            <li class="disabled"></li>
                        {% endif %}
                        {% for pages in page_obj.paginator.page_range %}
                            {% if page_obj.number == pages %}
						        <li><a href="#">{{pages}}</a></li>
                            {% else %}
                                  <li><a href="?{% url_replace request 'page' pages %}">{{pages}}</a></li>
                            {% endif %}
						{% endfor%}

                        {% if page_obj.has_next %}
						   <li><a href="?{% url_replace request 'page' page_obj.next_page_number %}">Next</a></li>
                        {% else %}
                            <li class="disabled"></li>
                        {% endif %}
					</ul>
				</nav>
                {% endif %}
			</section>

		</main>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>Books</title>
	<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">

	<!-- Link Swiper's CSS -->
	<link rel="stylesheet" href="{% static 'css/swiper.min.css'%}">
	<link rel="stylesheet" href="{% static 'css/styles.css' %}">

	<script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
	<script src="{% static 'js/script.js'%}"></script>

	{% block  styles %}
	{% endblock %}


</head>
<body>
	<div class="wrapper">
		<header class="header">
			<nav class="menu">
				<ul>
					<li><a href="/">BookWeb</a></li>
					<li><a href="/">Home</a></li>
					<li><a>Category</a>
						<ul>
							<li><a href="{% url 'books:book_category' 'fantasy' %}">Fantasy</a></li>
							<li><a href="{% url 'books:book_category' 'sci_fi' %}">Sci_fi</a></li>
							<li><a href="{% url 'books:book_category' 'horror' %}">Horror</a></li>
							<li><a href="{% url 'books:book_category' 'biographies' %}">Biographies</a></li>
							<li><a href="{% url 'books:book_category' 'romance' %}">Romance</a></li>
							<li><a href="{% url 'books:book_category' 'thrillers' %}">Thrillers</a></li>

						</ul>
					</li>
					<li><a href="{% url 'books:author_list'%}">Authors</a></li>
					<li class="mobsearch">
						<form class="mobform", method="GET">
							<input type="text" name="query" value="{{ request.GET.q}}" class="mobsearchfield" placeholder="Search...">
							<input type="submit" value="" class="mobsearchsubmit">
						</form>
					</li>
				</ul>
			</nav>
			<form class="search" method="GET" action="{% url 'books:book_search' %}">
				<input type="text" name="query" value="{{ request.GET.q }}" class="searchfield" placeholder="Search Book">
				<input type="submit" value="" class="searchsubmit">
			</form>

			<div class="toggle"><img src="{% static 'img/menu.svg' %} "></div>
		</header>



		{% block content %}
        {% endblock %}

		<footer class="footer">
			<div class="copyright"><p>Copyright &copy 2017 www.focusoncode.com</p></div>
			<div class="footermenu">
				<ul>
					<li><a href="/">Home</a></li>
				</ul>
			</div>

		</footer>
	</div>

<!-- Swiper JS -->
		<script src="{% static 'js/swiper.min.js'%}"></script>

		{% block scripts %}
        {% endblock %}

		<!-- Initialize Swiper -->
		<script>



		</script>
</body>
</html>